project:
    name: "VBFHbbcc_ML_Study"

dataset:
    train: "training_input_files/train.h5"
    val: "training_input_files/val.h5"
    norm: "training_input_files/norm.yaml"

training:
    batch_size: 32
    num_workers: 0
    num_epochs: 30
    learning_rate: 0.001
    weight_decay: 1e-5
    dropout: 0.1
    seed: 42
    shuffle: True
    device: "cpu"

model:
    inputs:
        event_features: 
            - mBB
            - pTBB
            - eventWeight
            - nJets20pt_central
            - nJets20pt_rap
            - dPhiBB
            - mJJ
            - dPhiJJ
            - dPhiBBJJ
            - dEtaJJ
            - dEtaBBJJ
            - pT_balance
            - centralMaxPt
            - mBB_angle
            - asymJJ
        object_features: 
            - VBFjetPt
            - VBFjetEta
            - GN2v01BinBJet
            - GN2v01BinVBfJet
            - GN2v01cBinBJet
            - GN2v01cBinVBfJet
            - NTrk500PVVBFJet
            - QGTransformer_ConstScoreVBFJet
    hidden_dim: 64 #embedding dimension
    output_dim: 64 #dimension before the final classification layer
    num_heads: 4
    num_encoder_layers: 6
    ff_dim: 128
    object_pooling: "GlobalAttentionPooling"
    class_label: label

plots:
    make_local_plots: True
    plot_path: "plots/"



