project:
    name: "VBFHbbcc_ML_Study"

dataset:
    train: "training_input_files/train.h5"
    val: "training_input_files/val.h5"
    norm: "training_input_files/norm.yaml"

training:
    batch_size: 128
    num_workers: 0
    num_epochs: 20
    learning_rate: 0.001
    weight_decay: 1e-5
    dropout: 0.1
    seed: 42
    shuffle: True
    device: "cpu"

model:
    inputs:
        event_features: 
            - pTBB
            - nJets20pt_central
            - nJets20pt_rap
            - dPhiBB
            - mJJ
            - dPhiJJ
            - dPhiBBJJ
            - dEtaJJ
            - dEtaBBJJ
            - pT_balance
            - centralMaxPt
            - asymJJ
        object_features: 
            - VBFjetPt
            - VBFjetEta
            - GN2v01BinBJet
            - GN2v01BinVBfJet
            - NTrk500PVVBFJet
    hidden_dim: 64 #embedding dimension
    output_dim: 64 #dimension before the final classification layer
    num_heads: 4
    num_encoder_layers: 6
    ff_dim: 128
    object_pooling: "GlobalAttentionPooling"
    class_label: label
    pos_label_weight: 3.4
    decorrelation_strategy: adversary_on_classifier #this is the type of algorithm to use for adversary
    mbb_bins: [ 0,80,100,115,130,200]
    adv_lambda: 100
plots:
    make_local_plots: True
    plot_path: "plots/"



